export const FETCH_WEEKLY_PLAN = 'FETCH_WEEKLY_PLAN';
export const FETCH_WEEKLY_PLAN_SUCCESSFULLY = 'FETCH_WEEKLY_PLAN_SUCCESSFULLY';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESSFULLY = 'FETCH_USER_SUCCESSFULLY';

